[tool.poetry]
name = "okama-dash"
version = "0.5.0"
description = "Python financial widgets with okama and Dash (plotly)"
authors = ["Sergey Kikevich <sergey@rostsber.ru>"]
license = "MIT"
readme = "README.md"
homepage = "https://okama.io/"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: End Users/Desktop",
    "Intended Audience :: Financial and Insurance Industry",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
packages = [{include = "okama_dash"}]

[tool.poetry.dependencies]
python = ">=3.8, <4.0.0"
okama = "^1.2.3"
dash = "^2.5.1"
dash-daq = "^0.5.0"
dash-bootstrap-components = "^1.2.0"
plotly = "^5.9.0"
Flask-Caching = "^2.0.0"
pandas = "<=1.6.0"
redis = "^4.4.0"

[tool.poetry.group.dev.dependencies]
pytest = "^6.0.0"
black = { version = "^22.6.0", optional = true }
gunicorn = "^20.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
